import {
	createGenericTemplate,
	deleteEmailTemplate,
} from '../emails/templates';
import { db, insertEmail, insertEntries } from './db';
import { Email, emails, entries, Entry } from './schema';

export async function seed() {
	await db.delete(emails);
	await insertEmail({
		to: '2',
		subject: 'Test Email {{lastName}}',
		content: 'It worked!\n{{Ticket}}',
		sendDate: 'immediate',
	} as Email);
	await insertEmail({
		name: 'After Registration',
		subject: 'Thanks for registering {{firstName}}!',
		content: "Here's your ticket: {{Ticket}}",
		status: 'hook',
	} as Email);
	await insertEmail({
		name: 'Ticket',
		content: 'This is a ticket',
		status: 'component',
	} as Email);

	await db.delete(entries);
	await insertEntries([
		{
			firstName: 'John',
			lastName: 'Doe',
			email: 'crusaders325@gmail.com',
			event1: true,
		},
		{
			firstName: 'Joseph',
			lastName: 'Martinez',
			email: 'ajbosco00@gmail.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Lee',
			lastName: 'Hill',
			email: 'kelly97@howard-lowe.biz',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Andre',
			lastName: 'Waters',
			email: 'craig78@smith.com',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Joseph',
			lastName: 'Baker',
			email: 'qgriffin@hamilton.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Rebekah',
			lastName: 'Howard',
			email: 'randallmartinez@hotmail.com',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Kelly',
			lastName: 'Bowman',
			email: 'marymartinez@richardson-ward.org',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Meghan',
			lastName: 'Hall',
			email: 'jane21@gmail.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Nichole',
			lastName: 'Alvarez',
			email: 'connerkyle@yahoo.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Marcus',
			lastName: 'Lewis',
			email: 'jacksonjasmine@yahoo.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Joshua',
			lastName: 'Cooper',
			email: 'philip00@yahoo.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Michael',
			lastName: 'Wilson',
			email: 'eatonwilliam@donaldson-conner.info',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'William',
			lastName: 'Cannon',
			email: 'hendersonthomas@noble.biz',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: '2024-07-23 19:19:42',
		},
		{
			firstName: 'Randall',
			lastName: 'Blake',
			email: 'charles53@campos-rose.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: '2024-08-02 19:19:42',
			updatedAt: null,
			canceledAt: '2024-09-14 19:19:42',
		},
		{
			firstName: 'Jason',
			lastName: 'Conway',
			email: 'markshaw@anderson.info',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Michael',
			lastName: 'Villanueva',
			email: 'thompsonjennifer@brown-smith.info',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Tyler',
			lastName: 'Wallace',
			email: 'shelly92@davis.com',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: '2024-09-03 19:19:42',
		},
		{
			firstName: 'Jerry',
			lastName: 'Maldonado',
			email: 'zcarter@garcia.biz',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Andrea',
			lastName: 'Hart',
			email: 'katherinewatkins@yahoo.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Brandon',
			lastName: 'Archer',
			email: 'scottmatthews@hotmail.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: '2024-10-06 19:19:42',
			canceledAt: null,
		},
		{
			firstName: 'Charles',
			lastName: 'Smith',
			email: 'holmesmarissa@clark.info',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: '2024-08-08 19:19:42',
			canceledAt: null,
		},
		{
			firstName: 'Miguel',
			lastName: 'Jackson',
			email: 'ecunningham@chapman.org',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Samuel',
			lastName: 'Patton',
			email: 'upittman@robinson.net',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Melissa',
			lastName: 'Hunter',
			email: 'anielsen@brown-rowe.com',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Tracy',
			lastName: 'Chapman',
			email: 'fcunningham@yahoo.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Amanda',
			lastName: 'Stewart',
			email: 'michelle12@gmail.com',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Dakota',
			lastName: 'Pham',
			email: 'pbeard@hotmail.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Amanda',
			lastName: 'Rodgers',
			email: 'michaelweeks@crawford.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Eric',
			lastName: 'Scott',
			email: 'james05@hotmail.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Christopher',
			lastName: 'West',
			email: 'schmidtdonna@yahoo.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Ashley',
			lastName: 'Bates',
			email: 'fpadilla@hotmail.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Christina',
			lastName: 'Andrews',
			email: 'ashleyfriedman@perez.info',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Joshua',
			lastName: 'Davies',
			email: 'duane52@hernandez.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Michael',
			lastName: 'Bowen',
			email: 'woodsrebecca@tyler-coleman.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'James',
			lastName: 'Roberts',
			email: 'richardsonjessica@gmail.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Michelle',
			lastName: 'Curtis',
			email: 'lisa68@mathews.org',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Edwin',
			lastName: 'Williams',
			email: 'madisonlester@hotmail.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'John',
			lastName: 'Armstrong',
			email: 'samuelmurray@yahoo.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Steven',
			lastName: 'Brown',
			email: 'shellyjoseph@hotmail.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Adrienne',
			lastName: 'Garrison',
			email: 'julie61@yahoo.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Shannon',
			lastName: 'Black',
			email: 'jacobwheeler@gmail.com',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Anna',
			lastName: 'Payne',
			email: 'michaelallen@gmail.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Taylor',
			lastName: 'Ramos',
			email: 'fhardy@schroeder.biz',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Nathaniel',
			lastName: 'Ellis',
			email: 'heidi41@townsend.info',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Shannon',
			lastName: 'Robinson',
			email: 'andrewcollins@mason.info',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Michael',
			lastName: 'Hall',
			email: 'mosesthomas@yahoo.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'James',
			lastName: 'Thomas',
			email: 'cody34@hotmail.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: '2024-09-25 19:19:42',
			updatedAt: '2024-09-10 19:19:42',
			canceledAt: '2024-07-27 19:19:42',
		},
		{
			firstName: 'Dana',
			lastName: 'Nichols',
			email: 'ashleyramirez@hartman.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: '2024-08-01 19:19:42',
			updatedAt: null,
			canceledAt: '2024-08-06 19:19:42',
		},
		{
			firstName: 'Bruce',
			lastName: 'Patterson',
			email: 'unguyen@hotmail.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Robert',
			lastName: 'Nunez',
			email: 'christophermckenzie@hotmail.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Brandon',
			lastName: 'Gomez',
			email: 'cherylmiller@barnes.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Ryan',
			lastName: 'Tucker',
			email: 'jacqueline38@hotmail.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Dean',
			lastName: 'Smith',
			email: 'pachecojennifer@lin-haney.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Tonya',
			lastName: 'Garcia',
			email: 'hrodriguez@torres.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Nicholas',
			lastName: 'Mack',
			email: 'jameskrueger@yahoo.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Mary',
			lastName: 'Black',
			email: 'srodriguez@hotmail.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'John',
			lastName: 'Nelson',
			email: 'robertsalejandro@hotmail.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Beverly',
			lastName: 'Castaneda',
			email: 'oneilldiana@sanchez-small.net',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Ana',
			lastName: 'Salazar',
			email: 'jbolton@hotmail.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Julie',
			lastName: 'Frazier',
			email: 'athomas@taylor-krueger.biz',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Richard',
			lastName: 'Mcneil',
			email: 'umiller@hotmail.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Steven',
			lastName: 'Powell',
			email: 'aramirez@hotmail.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Richard',
			lastName: 'Santos',
			email: 'erinbennett@anderson.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Emily',
			lastName: 'Reynolds',
			email: 'john43@hotmail.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Kelly',
			lastName: 'Kramer',
			email: 'laurie96@johnson.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Thomas',
			lastName: 'Collins',
			email: 'alexander91@yahoo.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Derek',
			lastName: 'Carson',
			email: 'michael34@kline.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Jeffrey',
			lastName: 'Murphy',
			email: 'stevegonzalez@bartlett.info',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Mark',
			lastName: 'Spears',
			email: 'rachelwright@english.biz',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Debra',
			lastName: 'Walker',
			email: 'xgarcia@anderson.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Margaret',
			lastName: 'Wright',
			email: 'dixonmonique@gmail.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Amanda',
			lastName: 'Weeks',
			email: 'pcrane@kim.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Kristin',
			lastName: 'Moore',
			email: 'oleach@gmail.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Roberta',
			lastName: 'Dawson',
			email: 'taylornicole@yahoo.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Jamie',
			lastName: 'Wilson',
			email: 'shanejones@hotmail.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Jessica',
			lastName: 'Collins',
			email: 'jaclynhall@scott-norton.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Ashley',
			lastName: 'Morgan',
			email: 'kevin86@gonzalez.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Ryan',
			lastName: 'Ellis',
			email: 'iirwin@yahoo.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Jeffrey',
			lastName: 'Williams',
			email: 'stevensjustin@yahoo.com',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Olivia',
			lastName: 'Pena',
			email: 'nelsonalexis@bates.com',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Desiree',
			lastName: 'Wu',
			email: 'norristimothy@white.biz',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Brittany',
			lastName: 'Martinez',
			email: 'grimesdaniel@hotmail.com',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Vicki',
			lastName: 'Holland',
			email: 'patrick36@gmail.com',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Lauren',
			lastName: 'Walker',
			email: 'norrischristina@jenkins-martin.com',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Heather',
			lastName: 'Lucas',
			email: 'gonzaleslisa@gentry.org',
			event1: false,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Lee',
			lastName: 'Booker',
			email: 'jeffreymedina@flores-henderson.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Marcus',
			lastName: 'Cox',
			email: 'erin19@martinez.com',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Danielle',
			lastName: 'Patel',
			email: 'garzakristen@dominguez-chung.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: '2024-09-14 19:19:42',
			updatedAt: '2024-10-03 19:19:42',
			canceledAt: null,
		},
		{
			firstName: 'Joseph',
			lastName: 'Velez',
			email: 'garciadavid@moreno-stewart.com',
			event1: false,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Leah',
			lastName: 'Duarte',
			email: 'patelcarolyn@yahoo.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Jeffrey',
			lastName: 'Maxwell',
			email: 'sprice@novak.com',
			event1: true,
			event2: false,
			event3: false,
			deletedAt: '2024-09-18 19:19:42',
			updatedAt: '2024-07-19 19:19:42',
			canceledAt: null,
		},
		{
			firstName: 'Nicholas',
			lastName: 'Johnson',
			email: 'nmurphy@gmail.com',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Stanley',
			lastName: 'Suarez',
			email: 'smithwilliam@morgan.info',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'William',
			lastName: 'Lane',
			email: 'robert50@medina.net',
			event1: true,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Victor',
			lastName: 'Garner',
			email: 'sarahgraham@gmail.com',
			event1: true,
			event2: true,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Angela',
			lastName: 'Griffin',
			email: 'hoodsean@yahoo.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Thomas',
			lastName: 'Norman',
			email: 'melissa35@singh.info',
			event1: false,
			event2: false,
			event3: true,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Carlos',
			lastName: 'Porter',
			email: 'xlane@kramer.biz',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Anita',
			lastName: 'Mullen',
			email: 'alexandersummers@gmail.com',
			event1: true,
			event2: true,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Lori',
			lastName: 'Williams',
			email: 'dalexander@thomas-hall.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
		{
			firstName: 'Brenda',
			lastName: 'Cook',
			email: 'maxwellcunningham@yahoo.com',
			event1: false,
			event2: false,
			event3: false,
			deletedAt: null,
			updatedAt: null,
			canceledAt: null,
		},
	] as Entry[]);

	console.log(`Seeding complete.`);
}
